define ROOT "F:/Projeler/TouchAMP/www/tetris"
define DOCROOT "F:/Projeler/TouchAMP/www/tetris"
<VirtualHost *:80>
ServerName tetris.test
DocumentRoot "${DOCROOT}"
<Directory "${DOCROOT}">
AllowOverride All
Require all granted
</Directory>
</VirtualHost>
<VirtualHost *:443>
ServerName tetris.test
DocumentRoot "${DOCROOT}"
SSLEngine on
SSLCertificateFile "F:/Projeler/TouchAMP/etc/ssl/tetris.test.crt"
SSLCertificateKeyFile "F:/Projeler/TouchAMP/etc/ssl/tetris.test.key"
<Directory "${DOCROOT}">
AllowOverride All
Require all granted
</Directory>
</VirtualHost>
