# SSL and PHP Configuration for Virtual Hosts and Projects

# PHP Module (PHP within the project)
LoadFile "${PHP_DIR}/libcrypto-3-x64.dll"
LoadFile "${PHP_DIR}/libssl-3-x64.dll"
LoadModule php_module "${PHP_DIR}/php8apache2_4.dll"
PHPINIDir "${PHP_DIR}"

<IfModule mime_module>
    AddType application/x-httpd-php .php
</IfModule>

# SSL Settings
Listen 443
SSLCipherSuite HIGH:!aNULL:!MD5:!RC4:!3DES:!CAMELLIA
SSLProxyCipherSuite HIGH:!aNULL:!MD5:!RC4:!3DES:!CAMELLIA
SSLHonorCipherOrder on
SSLProtocol TLSv1.2 TLSv1.3
SSLProxyProtocol TLSv1.2 TLSv1.3
SSLSessionCache "shmcb:logs/ssl_scache(512000)"
SSLSessionCacheTimeout 300

# phpMyAdmin Alias
Alias /phpmyadmin "${APP_DIR}/etc/apps/phpMyAdmin/"
<Directory "${APP_DIR}/etc/apps/phpMyAdmin/">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
    DirectoryIndex index.php index.html
</Directory>

# Include Virtual Hosts
IncludeOptional "${SITES_ENABLED_DIR}/*.conf"
